version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  app-prod:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
